### ISSUE TITLE
Typstyle Roadmap 2024

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typstyle#15]
Sorted by importance:

## Quality

- [x] Avoid bugs that cause render corruption #8
- [x] #16
- [x] Correctly handle incomplete code #6 

## Integration

- [x] Improve quality to a degree that it can be integrated into [tinymist](https://github.com/Myriad-Dreamin/tinymist)
- [ ] Range format #27 

## More Quality

- [x] integration test target bigger projects #20 

## Functionality

- [x] #31 #21 flavor detection

###  DSLs

- [ ] #17
- [ ] #59 

### Semantic format

- [ ] Use tinymist-analyze to get more info to help format.

### Math

- [ ] better handling for math alignments

## Performance

- [x] Consider reimplement the pretty printer: Currently impl could be exponential in some cases. This also brings more feature other than rust's pretty: https://github.com/fpottier/pprint

## Comment
- [ ] #46 
- [ ] #104

**Comment by Enter-tainer** [comment]
Let's move to #214！
