### ISSUE TITLE
Typstyle roadmap 2025

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typstyle#214]
**Typstyle Development Roadmap for 2025**

Over the past year, we’ve made significant progress in Typstyle, with most of the major functionalities outlined in #15 now implemented. A heartfelt thank you to all contributors for your invaluable efforts!

Today, Typstyle delivers consistent formatting quality and ensures document integrity, thanks to our robust testing framework. As we look ahead to 2025, our development goals are centered around three key pillars:

1. **Reduce No-Format Cases**  
2. **Smarter Formatting**  
3. **Enhanced Pretty Print Engine**  

---

### 1. Reduce No-Format Cases  

In 2024, we made substantial strides in reducing no-format cases, largely due to the exceptional work of @QuadnucYard. However, formatting is still disabled for certain scenarios, such as markup and math. These limitations are tracked [here](https://enter-tainer.github.io/typstyle/limitations/#overall).  

**Math:**  
- [ ] #132  
- [ ] #43  
- [ ] #22  

**Markup:**  
- [ ] #142  

---

### 2. Smarter Formatting  

2024 saw remarkable improvements in table and chain formatting. In 2025, we aim to extend these advancements to more DSLs (Domain-Specific Languages) and leverage **tinymist-query** to gain deeper semantic insights for enhanced code understanding.  

**Analysis:**  
- [ ] #17  
- [ ] #59  
- [ ] #212  
- [ ] #196  

**New Features:**  
- [ ] #212  
- [ ] #211  

---

### 3. Better Pretty Print Engine  

A more powerful pretty print engine will unlock advanced formatting techniques, further elevating Typstyle’s capabilities.  

- [ ] #95  
- [ ] #76  

---

We’re excited to continue pushing the boundaries of Typstyle in 2025 and look forward to collaborating with our community to achieve these goals. Thank you for your ongoing support and contributions!

**Comment by visserle** [comment]
Since I can't find it in the roadmap, would you mind sharing the current status of #104?

**Comment by Enter-tainer** [comment]
> Since I can't find it in the roadmap, would you mind sharing the current status of [#104](https://github.com/Enter-tainer/typstyle/issues/104)?

No updates on this unfortunately

**Comment by QuadnucYard** [comment]
## Work List

- [x] (markup) Reflow text. #260 
- [ ] (markup & code) Reorder import.
  - [x] Sort import items (in safe cases). #246 #268  
  - [ ] Sort import statements.
  - [ ] Group imports of the same sources.
- [ ] (math) Align by align points. #266 
  - [ ] Across func call args. 
- [ ] (code) Align table cells. 
- [ ] (code) Compact layout
  - [ ] (core) better pretty engine.
  - [x] last arg of func call. #261 #269
  - [ ] arrays, dictionaries of single item.
  - [ ] call chain.
- [ ] (markup & code) Format doc comments as typst source.

**Comment by nullzeta** [comment]
Should the README point to *2025* roadmap?
https://github.com/typstyle-rs/typstyle/blob/a9e3c8bedab2c5f6e18266d391205572b293c582/README.md?plain=1#L184

Thanks for your work!

**Comment by Enter-tainer** [comment]
> Should the README point to _2025_ roadmap?
> 
> [typstyle/README.md](https://github.com/typstyle-rs/typstyle/blob/a9e3c8bedab2c5f6e18266d391205572b293c582/README.md?plain=1#L184)
> 
> Line 184 in [a9e3c8b](/typstyle-rs/typstyle/commit/a9e3c8bedab2c5f6e18266d391205572b293c582)
> 
>  See the [tracking issue](https://github.com/typstyle-rs/typstyle/issues/15). 
> Thanks for your work!

Hi, Thanks for pointing out! Would you mind open a quick PR to fix it?

**Comment by nullzeta** [comment]
> Hi, Thanks for pointing out! Would you mind open a quick PR to fix it?

On this occasion i would like to throw in a few questions if you don't mind ;)
For the context, i am new to github and its rules(principles) for collaboration aren't clear to me yet.

The way i see the right approach to notify a developer about something minor (but not just a typo) like outdated/incorrect info in the docs/readme is to open an issue instead of a PR for the following reasons:
1. Now that one is aware about some "bug", they may want to not just fix it, but also expand on that / refactor that part(section).
    - Example: A long time passed since 2024 and i thought that now, before updating the readme, you may want to put some additional notes that section. Or, of course, may not.
2. Some "bugs", though can be relevant, may be known to the developer and they have broader vision of the project's future that just makes them leave that "bug" as is and that is intended.
    - Example: Just happened to me once.
 
?. Such changes are often super small and require 15 seconds from the developer to fix. But, given 1. and 2. it may be less hassle overall for them do fix that manually if one of "1." / "2." scenarios happens to be the case.

Even when someone's already opened an issue, i've seen developers asking the author to open a PR that adds mentioned (and maybe discussed in that issue ticket) fixes. In this particular example it seems even more confusing to me. Is the core intention of that to contribution count for the author of that issue or it simplifies the project owner's life somehow?

Tried my best while not being a native speaker so sorry i'm if something sounds confusing.
Thanks :)
